[package]
name = "finchers-runtime"
version = "0.11.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[features]
tls = ["native-tls", "tokio-tls"]

[dependencies]
finchers-core = { version = "0.11.0-dev", path = "../finchers-core" }

futures = "0.1.20"
http = "0.1.5"
hyper = { version = "0.11", features = ["compat"] }
tokio-core = "0.1"
tokio-io = "0.1"
net2 = "0.2"
num_cpus = "1.8"

native-tls = { version = "0.1", optional = true }
tokio-tls = { version = "0.1", optional = true }
