[package]
name = "finchers-runtime"
version = "0.11.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
finchers-core = { version = "0.11.0-dev", path = "../finchers-core" }

futures = "0.1.20"
http = "0.1.5"
hyper = { version = "0.11", features = ["compat"] }
tokio = "0.1.5"
