[package]
name = "finchers-core"
version = "0.11.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[features]
tls = ["native-tls", "tokio-tls"]

[dependencies]
hyper = { version = "0.11", features = ["compat"] }
mime = "0.3"
http = "0.1"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
net2 = "0.2"
num_cpus = "1.8"
bytes = "0.4"

native-tls = { version = "0.1", optional = true }
tokio-tls = { version = "0.1", optional = true }
