[package]
name = "finchers-core"
version = "0.11.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/finchers-rs/finchers.git"
homepage = "https://finchers-rs.github.io"
documentation = "https://docs.rs/finchers-core"
description = """
Core primitives for constructing asynchronous HTTP services
"""

[dependencies]
mime = "0.3"
http = "0.1"
futures = "0.1"
bytes = "0.4"
scoped-tls = "0.1.1"
either = "1.5.0"
failure = "0.1.2"
percent-encoding = "1.0"

[dependencies.hyper]
version = "0.11.24"
default-features = false
optional = true

[features]
default = ["hyper"]
nightly = []
