[package]
name = "finchers-core"
version = "0.11.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
hyper = { version = "0.11", features = ["compat"] }
mime = "0.3"
http = "0.1"
futures = "0.1"
bytes = "0.4"

