dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly-2018-08-14
      sudo: required
      addons:
        apt:
          packages:
            - libssl-dev
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
        - RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin || true
      script:
        - cargo clean
        - cargo test --features strict
        - cargo test -p example-todo
        # format check
        - cargo fmt -- --check
        # clippy
        - cargo clippy
      after_success:
        - >
            cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID \
                --packages finchers-core finchers

    - rust: nightly
      script:
        - cargo clean
        - cargo test --features strict
        - cargo test -p example-todo

    - rust: nightly-2018-08-14
      env: DEPLOY_DOCS
      before_script:
        - curl -sSLf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.0/mdbook-v0.2.0-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
        - chmod +x ./mdbook
      script:
        - cargo clean
        - cargo doc
        - ./mdbook build ./guide/
        - rm -f target/doc/.lock
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
