dist: trusty
sudo: false
language: rust
cache: cargo

branches:
  only:
    - master

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly-2018-01-31
      env: RUSTFMT_VERSION="0.3.7"

  allow_failures:
    - rust: nightly
    - rust: nightly-2018-01-31

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - bash .travis/install-rustfmt.sh

script:
  - if [[ -z "$RUSTFMT_VERSION" ]]; then cargo build; fi
  - if [[ -z "$RUSTFMT_VERSION" ]]; then cargo test; fi
  - if [[ -z "$RUSTFMT_VERSION" && "$TRAVIS_RUST_VERSION" == "stable" ]]; then cargo doc --no-deps; fi
  - if [[ -n "$RUSTFMT_VERSION" ]]; then cargo fmt -- --write-mode=diff; fi

after_success:
  - if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then bash .travis/upload-doc.sh; fi
#  - travis-cargo --only stable coveralls --no-sudo
