dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true

branches:
  only:
    - master

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly-2018-08-27
      sudo: required
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev
            - libelf-dev
            - libdw-dev
            - binutils-dev
      before_script:
        - rustup component add rustfmt-preview
        - rustup component add clippy-preview
        - cargo install cargo-update || true
        - cargo install cargo-kcov || true
        - cargo install-update -a
        - export CARGO_INCREMENTAL=0
      script:
        - cargo clean
        - cargo test --features strict
        # lints
        - cargo fmt -- --check
        - cargo clippy --features strict
        # examples
        - cargo test -p example-diesel
        - cargo test -p example-staticfiles
        - cargo test -p example-template-tera
        - cargo test -p example-todos
      after_success:
        - cargo kcov --print-install-kcov-sh | sh
        - cargo kcov -v --coveralls

    - rust: nightly
      env: LATEST_NIGHTLY
      script:
        - cargo clean
        - cargo test --all

    - rust: nightly-2018-08-27
      env: DEPLOY_DOCS
      before_script:
        - curl -sSLf https://github.com/rust-lang-nursery/mdBook/releases/download/v0.2.1/mdbook-v0.2.1-x86_64-unknown-linux-gnu.tar.gz | tar xzf -
        - chmod +x ./mdbook
      script:
        - cargo clean
        - cargo doc
        - ./mdbook build ./guide/
        - rm -f target/doc/.lock
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers
        target_branch: gh-pages
        local_dir: target/doc
        on:
          branch: master
