sudo: false
language: rust
cache: cargo

branches:
  only:
    - master

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

    - rust: nightly-2018-01-15
      env: CI_MODE="lint"

  allow_failures:
    - rust: nightly
    - rust: nightly-2018-01-15

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

before_script:
  - pip install --user 'travis-cargo<0.2'
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$CI_MODE" == "lint" ]]; then rustup component add rustfmt-preview; fi

script:
  - travis-cargo build
  - travis-cargo test
  - travis-cargo --only stable doc -- --no-deps

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo --only stable coveralls --no-sudo
  - if [[ "$CI_MODE" == "lint" ]]; then cargo fmt -- --write-mode=diff; fi