sudo: false
language: rust

branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - pip install --user 'travis-cargo<0.2'
  - export PATH=$HOME/.local/bin:$PATH

script:
  - travis-cargo build
  - travis-cargo build --only stable --features secure,tls
  - travis-cargo test
  - travis-cargo test --only stable --features secure,tls
  - travis-cargo doc --only stable --features secure,tls

after_success:
  - travis-cargo coveralls
  - travis-cargo --only stable doc-upload
