dist: trusty
sudo: false
language: rust

cache:
  - cargo
  - bundler

branches:
  only:
    - master

env:
  global:
    - STABLE_FEATURES="tls"
    - MDBOOK_VERSION="0.1.2"
    - RUSTFMT_VERSION="0.3.7"

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly-2018-01-31
      env: RUSTFMT="true"

  allow_failures:
    - rust: nightly
    - rust: nightly-2018-01-31

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

before_script:
  - 'export PATH=$HOME/.local/bin:$PATH'
  - '[[ -z "$RUSTFMT" ]] || bash .travis/install-rustfmt.sh'
  - '[[ -n "$RUSTFMT" ]] || bash .travis/install-mdbook.sh'

script:
  - '[[ -n "$RUSTFMT" ]] || bash .travis/script.sh'
  - '[[ -z "$RUSTFMT" ]] || cargo fmt -- --write-mode=diff'

after_success:
  - '[[ -n "$RUSTFMT" ]] || bash .travis/build-doc.sh'
  - '[[ -n "$RUSTFMT" ]] || bash .travis/deploy-doc.sh'
#  - travis-cargo --only stable coveralls --no-sudo

