dist: trusty
sudo: false
language: rust

cache:
  - apt: true
  - cargo: true
  - bundler: true
  - directories:
    - doc/target

branches:
  only:
    - master

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev
      - libelf-dev
      - cmake

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: stable
      sudo: true
      before_script:
        - rustup component add rustfmt-preview
        - cargo install cargo-kcov
        - cargo kcov --print-install-kcov-sh | sh -s
        - cargo clean
      script:
        - cargo test --all
        - cargo test --all --all-features
      after_success:
        - cargo fmt -- --write-mode=diff
        - cargo kcov -v --all --coveralls
      before_deploy:
        - cargo doc --all --all-features --no-deps
        - cargo install mdbook -f --version 0.1.2
        - bash doc/generate.sh
        - cp -a target/doc doc-upload/api
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        repo: finchers-rs/finchers-rs.github.io
        target_branch: master
        local_dir: doc-upload
        on:
          branch: master

    - rust: beta
      before_script:
        - cargo clean
      script:
        - cargo test --all
        - cargo test --all --all-features
      after_success:
        - cargo fmt -- --write-mode=diff

    - rust: nightly
      before_script:
        - cargo clean
      script:
        - cargo test --all
        - cargo test --all --all-features
      after_success:
        - cargo fmt -- --write-mode=diff
