dist: trusty
sudo: false
language: rust
cache: cargo

branches:
  only:
    - master

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    #- rust: nightly-2018-01-15
    #  env: CI_MODE="lint" CHANNEL="nightly-2018-01-15"

  allow_failures:
    - rust: nightly
    #- rust: nightly-2018-01-15

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - cmake

before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$CI_MODE" != "lint" ]]; then pip install --user 'travis-cargo<0.2'; fi
  #- if [[ "$CI_MODE" == "lint" ]]; then rustup run "${CHANNEL}" cargo install rustfmt-nightly --version 0.3.4 || true; fi

script:
  - if [[ "$CI_MODE" != "lint" ]]; then travis-cargo build; fi
  - if [[ "$CI_MODE" != "lint" ]]; then travis-cargo test; fi
  - if [[ "$CI_MODE" != "lint" ]]; then travis-cargo --only stable doc -- --no-deps; fi
  #- if [[ "$CI_MODE" == "lint" ]]; then rustup run "${CHANNEL}" cargo fmt -- --write-mode=diff; fi

after_success:
  - if [[ "$CI_MODE" != "lint" ]]; then travis-cargo --only stable doc-upload; fi
  - if [[ "$CI_MODE" != "lint" ]]; then travis-cargo --only stable coveralls --no-sudo; fi