[package]
name = "finchers"
version = "0.12.0-dev" # don't forget to update html_root_url in lib.rs
description = "A combinator library for builidng asynchronous HTTP services"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://finchers-rs.github.io/"
repository = "https://github.com/finchers-rs/finchers.git"
documentation = "https://docs.rs/finchers"
keywords = ["finchers", "web", "framework", "server"]
categories = ["web-programming::http-server"]

include = [
  "Cargo.toml",
  "src/**/*",
  "tests/**/*",
]

[badges]
travis-ci = { repository = "finchers-rs/finchers" }
coveralls = { repository = "finchers-rs/finchers" }
maintenance = { status = "actively-developed" }

[workspace]
members = [
  "finchers-core",
  "finchers-derive",

  "examples/basic-auth",
  "examples/form",
  "examples/todo",
]

[dependencies]
finchers-core = { version = "0.12.0-dev", path = "finchers-core" }
finchers-derive = { version = "0.12.0-dev", path = "finchers-derive" }

bytes = "0.4.9"
failure = "0.1.2"
futures = "0.1.23"
http = "0.1.10"
hyper = "0.12.7"
scoped-tls = "0.1.2"
slog = "2.3.2"
slog-async = "2.3.0"
slog-term = "2.4.0"
structopt = "0.2.10"
tokio = "0.1.7"

futures-core-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", branch = "master" }
futures-util-preview = { git = "https://github.com/rust-lang-nursery/futures-rs.git", branch = "master", features = ["tokio-compat"] }
#futures-core-preview = { version = "0.3.0-alpha.3" }
#futures-util-preview = { version = "0.3.0-alpha.3", features = ["tokio-compat"] }

[dev-dependencies]
bytes = "0.4.9"
