[package]
name = "finchers"
version = "0.1.3-pre"
description = "A combinator library for builidng HTTP services, based on Hyper and Futures"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/ubnt-intrepid/finchers.git"
documentation = "https://docs.rs/finchers"

[dependencies]
error-chain = "~0.10"
hyper = "~0.11"
futures = "~0.1"
tokio-core = "~0.1"
url = "~1.5"
serde = "~1.0"
serde_json = "~1.0"

[dev-dependencies]
serde_derive = "~1.0"
lazy_static = "~0.2"
