[package]
name = "finchers"
version = "0.12.0-dev" # don't forget to update html_root_url in lib.rs
description = "A combinator library for builidng asynchronous HTTP services"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://finchers-rs.github.io/"
repository = "https://github.com/finchers-rs/finchers.git"
documentation = "https://docs.rs/finchers"
keywords = ["finchers", "web", "framework", "server"]
categories = ["web-programming::http-server"]

include = [
  "Cargo.toml",
  "src/**/*",
  "tests/**/*",
]

[badges]
travis-ci = { repository = "finchers-rs/finchers" }
coveralls = { repository = "finchers-rs/finchers" }
maintenance = { status = "actively-developed" }

[workspace]
members = [
  "finchers-core",
  "finchers-derive",
  "finchers-ext",
  "finchers-http",
  "finchers-runtime",
  "finchers-test",

  "examples/basic-auth",
  "examples/form",
  "examples/todo",
]

[dependencies]
finchers-core = { version = "0.11.0", path = "finchers-core" }
finchers-derive = { version = "0.11.0", path = "finchers-derive" }
finchers-ext = { version = "0.11.0", path = "finchers-ext" }
finchers-http = { version = "0.11.0", path = "finchers-http" }
finchers-runtime = { version = "0.11.0", path = "finchers-runtime" }
finchers-test = { version = "0.11.0", path = "finchers-test" }

[dev-dependencies]
http = "0.1"
