[package]
name = "finchers"
version = "0.4.1-pre"
description = "A combinator library for builidng HTTP services, based on Hyper and Futures"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/finchers-rs/finchers.git"
documentation = "https://docs.rs/finchers"

[dependencies]
hyper = "~0.11"
futures = "^0.1.15"
tokio-core = "~0.1"
tokio-proto = "~0.1"
tokio-service = "~0.1"
url = "~1.5"
serde = "~1.0"
serde_json = "~1.0"
net2 = "~0.2"

[dev-dependencies]
serde_derive = "~1.0"
lazy_static = "~0.2"
tokio-proto = "~0.1"
num_cpus = "~1.6"
