[package]
name = "finchers"
version = "0.0.1"
description = "A combinator library for builidng HTTP services of Hyper"
license = "MIT/Apache-2.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
homepage = "https://github.com/ubnt-intrepid/finchers"
repository = "https://github.com/ubnt-intrepid/finchers.git"

[dependencies]
error-chain = "~0.10"
hyper = "~0.11"
futures = "~0.1"
tokio-core = "~0.1"
url = "~1.5"
