[package]
name = "finchers"
version = "0.11.0-dev" # don't forget to update html_root_url in lib.rs
description = "A combinator library for builidng asynchronous HTTP services"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
homepage = "https://finchers-rs.github.io/"
repository = "https://github.com/finchers-rs/finchers.git"
documentation = "https://docs.rs/finchers"
keywords = ["finchers", "web", "framework", "server"]
categories = ["web-programming::http-server"]

[badges]
travis-ci = { repository = "finchers-rs/finchers" }
coveralls = { repository = "finchers-rs/finchers" }
maintenance = { status = "actively-developed" }

[workspace]
members = [
  "finchers-core",
  "finchers-derive",
  "finchers-endpoint",
  "finchers-json",
  "finchers-runtime",
  "finchers-urlencoded",
  "finchers-test",

  "examples/form",
  "examples/todo",
]

[dependencies]
finchers-core = { version = "0.11.0-dev", path = "finchers-core" }
finchers-derive = { version = "0.11.0-dev", path = "finchers-derive" }
finchers-endpoint = { version = "0.11.0-dev", path = "finchers-endpoint" }
finchers-runtime = { version = "0.11.0-dev", path = "finchers-runtime" }
finchers-test = { version = "0.11.0-dev", path = "finchers-test" }

finchers-json = { version = "0.11.0-dev", path = "finchers-json" }
finchers-urlencoded = { version = "0.11.0-dev", path = "finchers-urlencoded" }

mime = "0.3"
http = "0.1"
futures = "0.1"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
