[package]
name = "finchers"
version = "0.6.0"
description = "A combinator library for builidng HTTP services, based on Hyper and Futures"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/finchers-rs/finchers.git"
documentation = "https://docs.rs/finchers"

[dependencies]
hyper = "0.11"
futures = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
net2 = "0.2"
cookie = { version = "0.10", features = ["secure", "percent-encode"] }

url = "1.6"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
error-chain = "0.11"
