cargo-features = ["edition"]

[package]
name = "example-todos"
version = "0.0.0"
edition = "2018"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]
publish = false

[[bin]]
name = "todos"
path = "src/main.rs"
doc = false

[dependencies]
finchers = { path = "../.." }
futures-preview = "0.3.0-alpha.3"
serde = { version = "1.0", features = ["derive"] }
failure = "0.1"
