title: finchers
baseurl: ""
url: "https://github.com/finchers-rs/finchers"
theme: jekyll-theme-minimal

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

project_url: https://github.com/finchers-rs
repository_url: https://github.com/finchers-rs/finchers
docs_url: https://docs.rs/finchers
