[package]
name = "example-form"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[[bin]]
name = "form"
path = "src/main.rs"
doc = false

[dependencies]
finchers = { path = "../.." }
http = "0.1.5"
serde = { version = "1.0", features = ["derive"] }
