title: finchers
url: "https://github.com/finchers-rs/"
baseurl: ""
theme: jekyll-theme-minimal

exclude:
  - target/
  - tests/
  - build.rs
  - Cargo.toml
  - Cargo.lock
  - generate.sh
  - lib.rs

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
