[package]
name = "finchers-urlencoded"
version = "0.11.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
finchers = { version = "0.11.0-dev", path = "../finchers" }

futures = "0.1"
url = "1.6"
mime = "0.3"
serde = "1.0"
serde_qs = "0.3"

[dev-dependencies]
serde_derive = "1.0"
http = "0.1"
