[package]
name = "example-todo"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[[bin]]
name = "todo"
path = "src/main.rs"
doc = false

[dependencies]
finchers = { path = "../.." }
http = "0.1.5"
failure = "0.1"
serde = { version = "1.0", features = ["derive"] }
