[package]
name = "example-todo"
version = "0.1.0"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
finchers = { path = "../../src/finchers" }
finchers-json = { path = "../../src/finchers-json" }

http = "0.1"
