[package]
name = "finchers-urlencoded"
version = "0.11.0-dev"
authors = ["Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>"]

[dependencies]
finchers = { version = "0.11.0-dev", path = "../finchers" }
serde = "1.0"
serde_qs = "0.3"
